---
title: "05_pcst-TF-targets_loci_activity"
author: "Jana Braunger"
date: '2022-06-30'
output: BiocStyle::html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
BiocStyle::html_document 

dir <- "/Users/janabraunger/Documents/Studium/Master/Boston/Masterarbeit/"
figdir = paste0(dir, "Figures/pcst_results/")
if(!dir.exists(figdir)) dir.create(figdir)
knitr::opts_chunk$set(dev = c("png", "pdf"), fig.path = figdir)
options(scipen = 999) 
```

```{r load_libraries, message = FALSE, warning = FALSE}
library(tidyverse)
library(magrittr)
library(biomaRt)
```


# Get loci for selected genes
```{r subsampling, eval = FALSE}
# Load data frame with gene selection
data <- read.delim(paste0(dir, "Data/DE_genes.csv"), 
                   sep = ",", header = TRUE) %>%
  dplyr::rename(gene = targets)

# Query gene information from biomart
mart <- useEnsembl(biomart = "ensembl", 
                   dataset = "hsapiens_gene_ensembl", 
                   mirror = "uswest")
gene_annotations <- getBM(filters="external_gene_name", 
                          attributes=c("external_gene_name", 
                                       "chromosome_name", "start_position", 
                                       "end_position", "description"), 
                          values=unique(data$gene), mart=mart) %>%
  data.frame() %>%
  arrange(chromosome_name) %>%
  group_by(external_gene_name) %>%
  summarize(chr = dplyr::first(chromosome_name), start = dplyr::first(start_position), 
            end = dplyr::first(end_position), description = dplyr::first(description)) %>%
  dplyr::rename(gene = external_gene_name)

# Add loci to gene dataframe
data_loci <- data %>%
  left_join(gene_annotations, by = "gene") %>%
  mutate(locus = paste0("chr_", chr, "_loc_", 
                        plyr::round_any(start, 250000, floor))) %>%
  subset(select = c(gene, net, locus))
```


# Add activity of selected loci in IMR90 and old-fibroblasts
```{r}
IMR90 <- read.csv(paste0(file_path, "Data/IMR90_cosine_wo_PC.txt")) %>%
  dplyr::rename(locus = X0) %>%
  mutate(young_activity = "young:active")
old_fibroblasts <- read.csv(paste0(file_path, "Data/old_fibroblasts_cosine_wo_PC.txt")) %>%
  dplyr::rename(locus = X0) %>%
  mutate(old_activity = "old:active")

# add for each gene whether corresponding loci is active or inactive based on the HiC clustering in IMR90 and GM23248
activity <- data_loci %>%
  mutate(net = factor(net, levels = c('young', 'middle', 'old'))) %>%
  left_join(IMR90) %>% 
  replace_na(list(young_activity = "young:inactive")) %>%
  left_join(old_fibroblasts) %>% 
  replace_na(list(old_activity = "old:inactive")) %>%
  mutate(development = factor(paste0(young_activity, "_", old_activity), 
        levels = c("young:active_old:active", "young:active_old:inactive", "young:inactive_old:active", "young:inactive_old:inactive")))
# Save results
write.csv(activity, paste0(dir, "Data/DE_targets_loci.csv"), row.names = FALSE)

head(activity)
```

```{r}
ggplot(activity, aes(x = development, fill = development)) +
  geom_bar() +
  facet_wrap(~net) +
  theme_bw() +
  theme(axis.text.x=element_blank(), 
        axis.ticks.x=element_blank()) + 
  theme(text = element_text(size = 17))
```

```{r}
n_per_net <- group_by(activity, net) %>% summarize(n_total = n())
activity_old_fib <- group_by(activity, net, old_activity) %>% 
  summarize(n= n()) %>%
  filter(old_activity == "old:active") %>%
  mutate(celltype = "old_fibroblasts")
activity_young_fib <- group_by(activity, net, young_activity) %>% 
  summarize(n= n()) %>%
  filter(young_activity == "young:active") %>%
  mutate(celltype = "young_fibroblasts")

activity_percent <- bind_rows(activity_young_fib, activity_old_fib) %>%
  left_join(n_per_net) %>%
  mutate(percent = n/n_total) %>%
  mutate(celltype = factor(celltype, levels = c('young_fibroblasts', 'old_fibroblasts')))

ggplot(activity_percent, aes(x = celltype, y = percent, fill = celltype)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~net) +
  theme_bw()+
  theme(axis.text.x=element_blank(), 
        axis.ticks.x=element_blank()) +
  theme(text = element_text(size = 17))
```


# Get loci of FOS's DE targets
```{r FOS, eval = FALSE}
# Gene selection
TF_targets <- read.delim(paste0(dir, "Data/tf-target-information.txt")) %>%
  subset(select = c("TF", "target")) %>%
  distinct() 
p_0.05 <- read.delim(paste0(dir, "Data/DE_var_p_n_200.csv"), sep = ",") %>%
  filter(transition == "fc_61-85_86-96")
genes <- filter(TF_targets, TF == "FOS") %>%
  filter(target %in% p_0.05$gene)

# Query gene information from biomart
mart <- useEnsembl(biomart = "ensembl", 
                   dataset = "hsapiens_gene_ensembl", 
                   mirror = "useast")
gene_annotations <- getBM(filters="external_gene_name", 
                          attributes=c("external_gene_name", 
                                       "chromosome_name", "start_position", 
                                       "end_position", "description"), 
                          values=c(genes$target, "FOS"), mart=mart) %>%
  data.frame() %>%
  arrange(chromosome_name) %>%
  group_by(external_gene_name) %>%
  summarize(chr = dplyr::first(chromosome_name), start = dplyr::first(start_position), 
            end = dplyr::first(end_position), description = dplyr::first(description)) %>%
  dplyr::rename(gene = external_gene_name)

# Add loci to gene dataframe
data_loci <- gene_annotations %>%
  mutate(locus = paste0("chr_", chr, "_loc_", 
                        plyr::round_any(start, 250000, floor))) %>%
  filter(chr %in% as.character(seq(1,22,1))) %>%
  arrange(as.numeric(chr), start) %>%
  subset(select = c(gene, locus))
write.csv(data_loci, paste0(dir, "Data/DE_targets_FOS.csv"), row.names = FALSE)
```


# Get loci of all genes
```{r all_loci, eval = FALSE}
# Gene selection
genes <- read.delim(paste0(dir, "Data/count_data.csv"), sep = ",")$gene

# Query gene information from biomart
mart <- useEnsembl(biomart = "ensembl", 
                   dataset = "hsapiens_gene_ensembl", 
                   mirror = "useast")
gene_annotations <- getBM(filters="external_gene_name", 
                          attributes=c("external_gene_name", 
                                       "chromosome_name", "start_position", 
                                       "end_position", "description"), 
                          values=c(genes), mart=mart) %>%
  data.frame() %>%
  arrange(chromosome_name) %>%
  group_by(external_gene_name) %>%
  summarize(chr = dplyr::first(chromosome_name), start = dplyr::first(start_position), 
            end = dplyr::first(end_position), description = dplyr::first(description)) %>%
  dplyr::rename(gene = external_gene_name)

# Add loci to gene dataframe
data_loci <- gene_annotations %>%
  mutate(locus = paste0("chr_", chr, "_loc_", 
                        plyr::round_any(start, 250000, floor))) %>%
  filter(chr %in% as.character(seq(1,22,1))) %>%
  arrange(as.numeric(chr), start) %>%
  subset(select = c(gene, locus))

write.csv(data_loci, paste0(dir, "Data/all_gene_loci.csv"), row.names = FALSE)
```


# Add expression and activity annotation for TF-target interactions
```{r}
# Load TF targets
TF_targets <- read.delim(paste0(dir, "Data/tf-target-information.txt")) %>%
  subset(select = c("TF", "target")) %>%
  distinct() 

# Add DE annotation
p_0.05 <- read.delim(paste0(dir, "Data/DE_var_p_n_200.csv"), sep = ",")
TF_targets %<>% mutate(DE = ifelse(target %in% p_0.05$gene, 'True', 'False'))

# Add expression annotation
mean_counts <- read.delim(paste0(dir, "Data/mean_counts.csv"), sep = ",") %>%
  group_by(gene, age_group) %>%
  summarize(counts = mean(counts))
TF_targets %<>% mutate(expressed = ifelse(target %in% mean_counts$gene, 'True', 'False'))

# Add corresponding loci for targets
gene_loci <- read.delim(paste0(dir, "Data/all_gene_loci.csv"), sep = ",") %>%
  dplyr::rename('target' = 'gene')
TF_targets %<>% left_join(gene_loci)

# Add loci activity
IMR90 <- read.csv(paste0(file_path, "Data/IMR90_cosine_wo_PC.txt")) %>%
  dplyr::rename(locus = X0) %>%
  mutate(young_activity = "young:active")
old_fibroblasts <- read.csv(paste0(file_path, "Data/old_fibroblasts_cosine_wo_PC.txt")) %>%
  dplyr::rename(locus = X0) %>%
  mutate(old_activity = "old:active")
TF_targets %<>%
  left_join(IMR90) %>% 
  replace_na(list(young_activity = "young:inactive")) %>%
  left_join(old_fibroblasts) %>% 
  replace_na(list(old_activity = "old:inactive")) %>%
  mutate(development = factor(paste0(young_activity, "_", old_activity), 
        levels = c("young:active_old:active", "young:active_old:inactive", "young:inactive_old:active", "young:inactive_old:inactive")))

# Save results
write.csv(TF_targets, paste0(dir, "Data/tf_targets_anno.csv"), row.names = FALSE)
```
