include("CGPmap.jl");

#The starting point of the CGPmap is the genome-wide Hi-C contact map.
#The file ENCODE3-A549C-HindIII-R1__hg19__genome__C-40000-raw.hdf5 is an example.

###READ raw map stored in HDF5 format#######
filename="ENCODE3-A549C-HindIII-R1__hg19__genome__C-40000-raw.hdf5";
c=h5open(filename,"r") do file
	read(file);
end
A=c["interactions"];
bin2loc=c["bin_positions"];
chr2bins=c["chr_bin_range"];
all_chr=c["chrs"];

#The arrays bin2loc, chr2bins, all_chr store information of binning. They can be generated by:
hg19_info=define_hg19_genome();
bin_size=40000;
chr2bins,bin2loc=generate_arbitrary_mapping_files(hg19_info,bin_size);

#The array A is the contact map. It could be read from other file format, for instance, using
#input file generated by HiC-Pro, with 3 columns: row_index, column_index, entry
#read_simple_contact_map(input_file,hg19_info,bin_size);

########################################################################################################

###Define G2B_dict that maps every gene to the desired bin in the whole-genome contact map.
#A precalculated version for hg19 can be loaded via:
#d1=load("./G2B_dict.jld");
#G2B_dict=d1["G2B_dict"];

#or be calculated by inputting the genomic position of every gene.
annot_file="./all_exp_TPM_gencode19_pc_nr_no_mt.mat";
Gene, ENSG, strand, gene_st, gene_ed, chr, celltype, TPM, TPM_pe=load_annotation(annot_file);
G2B_dict=get_gene_to_bin_mapping(Gene,chr,gene_st,gene_ed,bin2loc);

###WGPmap is the weighted gene proximity map based on raw counts
println("Constructing weighted gene proximity map... (20227 genes in total)")
WGPmap=construct_GPC(A,Gene,G2B_dict);

WGPmap_aux=generate_GPC_null_aux(hg19_info,gene_st,gene_ed,chr,bin_size,WGPmap);

### Null model for the 1D component
err_threshold=1e-10;
println("Null model error is decreasing...")
Null_model_1D=generate_GPC_null(WGPmap,WGPmap_aux,err_threshold);

###Corrected Gene Proximity Map is obtained by subtracting the null model from the weighted gene proximity map
CGPmap = WGPmap - Null_model_1D;
