---
title: "STRING_scores"
author: "Jana"
date: '2022-05-16'
output: BiocStyle::html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
BiocStyle::html_document 

file_path <- "/Users/janabraunger/Documents/Studium/Master/Boston/Masterarbeit/"
figdir = paste0(file_path, "Figures/STRING_DE_0_10/")
if(!dir.exists(figdir)) dir.create(figdir)
knitr::opts_chunk$set(dev = c("png", "pdf"), fig.path = figdir)
```


```{r load_libraries, message = FALSE, warning = FALSE}
library(tidyverse)
library(magrittr )
library(ggplot2)
library(UpSetR)
```

# Load STRING interaction network

```{r}
interactions <- read.delim(paste0(file_path, "Data/9606.protein.physical.links.full.v11.5.txt"), sep = " ")
head(interactions)
```

# General statistics of the score types

## Reported interactions per score
```{r score_percentages}
interactions_long <- gather(interactions, key = score_name, value = score, 
                            -c(protein1, protein2)) %>%
  filter(score != 0) %>%
  mutate(interaction = paste0(protein1, "_", protein2))

occurences <- filter(interactions_long, score_name != "combined_score") %>%
  group_by(score_name) %>% 
  summarize(n = n()) %>%
  mutate(percent = n / nrow(interactions)) %>%
  arrange(desc(percent))

ggplot(occurences, aes(x = reorder(score_name, percent), y = percent)) +
  geom_bar(stat="identity") + 
  coord_flip() +
  xlab("") +
  theme_bw()
```


## Distributions of the score types

**Histogram of the score types**
```{r hist_scores_non_zero}
ggplot(interactions_long, aes(x = score)) + 
  geom_histogram() + 
  facet_wrap(~score_name, scales = "free_y") +
  theme_bw()
```

**Stacked histogram**
```{r hist_scores_stacked}
ggplot(filter(interactions_long, score_name != "combined_score"), aes(x = score, fill = score_name)) + 
  geom_histogram() +
  theme_bw()
```

**Percentages of each score type per bin**
```{r hist_scores_percent}
ggplot(filter(interactions_long, score_name != "combined_score"), aes(x = score, fill = score_name)) + 
  geom_histogram(position = 'fill') +
  theme_bw()
```


## How often are multiple score types reported for an interaction?
```{r}
#split interaction_long into list of groups
top_list <- filter(interactions_long, score_name != "combined_score") %>% 
  mutate(score_name = factor(score_name, levels = unique(interactions_long$score_name))) %>%
  group_by(score_name) %>% 
  group_split()
names(top_list) <- unique(interactions_long$score_name)[1:5]
top_list <- lapply(top_list, function(list) list$interaction)

upset(fromList(top_list), order.by = "freq", nsets = 8,
       mainbar.y.label = "Intersections", sets.x.label = "Interactions",
       text.scale = c(1.5, 1.5, 1, 1, 1.5, 1.5), nintersects = 10)
```


